name: debug_kit_example
description: "DebugKit example."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  debug_kit:
    path: ../packages/debug_kit
  debug_kit_http:
    path: ../packages/debug_kit_http
  http_middleware:
    git:
      url: https://github.com/andyduke/dart_http_middleware.git
      path: package
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  logging: ^1.2.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
